version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=TEST2
      - SPRING_DATASOURCE_PASSWORD=test2

  frontend-react:
    build: ./frontend-react
    ports:
      - "3000:80"
    depends_on:
      - backend

  frontend-vue:
    build: ./frontend-vue
    ports:
      - "3001:80"
    depends_on:
      - backend

  db:
    image: gvenzl/oracle-xe:latest
    restart: always
    environment:
      - ORACLE_PASSWORD=test2
      - APP_USER=TEST2
      - APP_USER_PASSWORD=test2
    ports:
      - "1521:1521"
    volumes:
      - db_data:/opt/oracle/oradata

volumes:
  db_data:
