version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "${HOST_BACKEND_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}

  frontend-react:
    build: ./frontend-react
    ports:
      - "${HOST_REACT_PORT}:80"
    depends_on:
      - backend

  frontend-vue:
    build: ./frontend-vue
    ports:
      - "${HOST_VUE_PORT}:80"
    depends_on:
      - backend
