version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8088:8080"
    environment:
      JAVA_OPTS: "-DDB_URL=${DB_URL} -DDB_USERNAME=${DB_USERNAME} -DDB_PASSWORD=${DB_PASSWORD}"
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend-react:
    build: ./frontend-react
    ports:
      - "8081:80"

  frontend-vue:
    build: ./frontend-vue
    ports:
      - "8082:80"
